config/routes.rb
Yakob::Application.routes.draw do
  root :to => 'home#index'

  

  

  

  

  

  

  

  match 'admin' => 'admin/dashboard#index'

  

  devise_for :users
  namespace "admin" do
    resources :users
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
 
    if user.role? :admin
      can :manage, :all
    # elsif user.role? :writter
    #   can :manage, [Post, Asset]
    # elsif user.role? :memeber
    #   can :read, [MemberPost, Asset]
    #   # manage posts, assets user owns
    #   can :manage, Post do |p|
    #     p.try(:owner) == user
    #   end
    #   can :manage, Asset do |a|
    #     a.try(:owner) == user
    #   end
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users

  def self.sanitize role
    role.to_s.humanize.split(' ').each{ |word| word.capitalize! }.join(' ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  devise :database_authenticatable, :token_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  default_scope :conditions => { :deleted_at => nil }
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false, :scope => :deleted_at
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_friendly_id :name, :use_slug => true, :strip_non_ascii => true

  
  def role?(role)
    return !!self.roles.find_by_name( Role.sanitize role )
  end

def destroy
    self.update_attribute(:deleted_at, Time.now.utc)
  end

  def self.find_with_destroyed *args
    self.with_exclusive_scope { find(*args) }
  end

  def self.find_only_destroyed
    self.with_exclusive_scope :find => { :conditions => "deleted_at IS NOT NULL" } do
      all
    end
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :find_user, :only => [:edit, :update, :destroy]
    
  def find_user
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.paginate :page => params[:page], :per_page => 50
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.role_ids = params[:user][:role_ids] if current_user.role? :admin
    if @user.save
      flash[:notice] = "User created!"
      redirect_to admin_users_url
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    params[:user][:role_ids] ||= []
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?

        @user.send(:attributes=, { :role_ids => params[:user][:role_ids] }, false) if current_user.role? :admin
    params[:user].delete(:role_ids)
    
if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated #{@user.name}."
      redirect_to admin_users_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "User deleted."
    redirect_to admin_users_url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access Denied"
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/dashboard/index.html.haml
%h1 Yakob Admin

app/views/admin/shared/_end_scripts.html.haml
= include_javascripts :common

app/views/admin/shared/_footer.html.haml
%footer#main_admin_footer

app/views/admin/shared/_header.html.haml
%header#main_admin_header
  %h1= link_to 'Yakob', root_path
= render 'admin/shared/messages'
%nav#main_admin_nav
  %ul
    %li= link_to 'Home', root_path    
  %ul#user_admin_nav
    = render 'devise/menu/login_items'

app/views/admin/shared/_messages.html.haml
- if flash[:notice]
  %div#messenger{:class => "flasher"}= flash[:notice]
- if flash[:error]
  %div#error{:class => "flasher"}= flash[:error]

app/views/admin/users/_form.html.haml
= form_for([:admin, @user])  do |f|
  .form_errors
    = f.error_messages
  %fieldset#user_form
    .form_row
      = f.label :name
      = f.text_field :name
    .form_row
      = f.label :email
      = f.text_field :email
    .form_row
      = f.label :password
      = f.password_field :password
    .form_row
      = f.label :password_confirmation
      = f.password_field :password_confirmation
    .form_row
      - Role.find(:all, :order => "name").each do |role|
        .check_box_item
          = check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role), :id => "user_role_#{role.id}"
          %label{:for => "user_role_#{role.id}"}= role.name.humanize
    .form_row.form_row_button
      = f.submit "Save"

app/views/admin/users/edit.html.haml
= render :partial => "form"

app/views/admin/users/index.html.haml
- if !@users.blank?
  %table
    %thead
      %tr
        %th Name
        %th Email
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, edit_admin_user_path(user), :class => 'edit_link'
          %td= user.email
          %td
            - if user.id != current_user.id
              = link_to "Delete", admin_user_path(user), :confirm => 'Are you sure?', :method => :delete, :class => 'delete_link'
            - else
              That's you!
  = will_paginate @users
- else
  %p No users

app/views/admin/users/new.html.haml
= render :partial => "form"

app/views/home/index.html.haml
%h1 Yakob

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html; charset=utf-8'}
    %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}
    %title 
      Yakob
      = yield(:title)
    %meta{:name => 'viewport', :content => 'width=device-width; initial-scale=1.0'}
    = csrf_meta_tag
    %link{:rel => "shortcut icon", :href => "/images/favicon.ico", :type => "image/x-icon"}
    /[if lt IE 9]
      %script{:type => "text/javascript", :src  => "/javascripts/shiv.js"}
    = include_stylesheets :admin, :media => 'all'
    = yield(:head)
    /[if IE 7]
      = stylesheet_link_tag 'ie7', :media => 'all'
    /[if IE 8]
      = stylesheet_link_tag 'ie8', :media => 'all'
  %body
    #container
      = render :partial => "admin/shared/header"
      %section#content
        = yield
      #pusher
    = render :partial => "admin/shared/footer"
    = render :partial => "admin/shared/end_scripts"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html; charset=utf-8'}
    %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}
    %title 
      Yakob
      = yield(:title)
    %meta{:name => 'description', :content => ''}
    %meta{:name => 'author', :content => ''}
    %meta{:name => 'viewport', :content => 'width=device-width; initial-scale=1.0'}
    = csrf_meta_tag
    %link{:rel => "shortcut icon", :href => "/images/favicon.ico", :type => "image/x-icon"}
    %link{:rel => "apple-touch-icon", :href => "/images/ati.png"}
    /[if lt IE 9]
      %script{:type => "text/javascript", :src  => "/javascripts/shiv.js"}
    = include_stylesheets :main, :media => 'all'
    = yield(:head)
    /[if IE 7]
      = stylesheet_link_tag 'ie7', :media => 'all'
    /[if IE 8]
      = stylesheet_link_tag 'ie8', :media => 'all'
  %body
    #container
      = render :partial => "shared/header"
      %section#content
        = yield
      #pusher
    = render :partial => "shared/footer"
    = render :partial => "shared/end_scripts"

app/views/shared/_end_scripts.html.haml
= include_javascripts :common

app/views/shared/_footer.html.haml
%footer#main_footer

app/views/shared/_header.html.haml
%header#main_header
  %h1= link_to 'Yakob', root_path
= render 'shared/messages'
%nav#main_nav
  %ul
    %li= link_to 'Home', root_path
  %ul#user_nav
    = render 'devise/menu/login_items'

app/views/shared/_messages.html.haml
- if flash[:notice]
  %div#messenger{:class => "flasher"}= flash[:notice]
- if flash[:error]
  %div#error{:class => "flasher"}= flash[:error]